# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{unit-hosting}
  s.version = "0.1.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Yoshihiro TAKAHARA"]
  s.date = %q{2011-03-08}
  s.default_executable = %q{unit-hosting}
  s.description = %q{This is a command to manage virtual servers on UnitHosting(http://www.unit-hosting.com).}
  s.email = %q{y.takahara@gmail.com}
  s.executables = ["unit-hosting"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/unit-hosting",
    "lib/unit-hosting.rb",
    "lib/unit-hosting/agent.rb",
    "lib/unit-hosting/api.rb",
    "lib/unit-hosting/api/base.rb",
    "lib/unit-hosting/api/vm.rb",
    "lib/unit-hosting/api/vm_group.rb",
    "lib/unit-hosting/api/vm_recipe.rb",
    "lib/unit-hosting/cache.rb",
    "lib/unit-hosting/cli.rb",
    "lib/unit-hosting/commands.rb",
    "lib/unit-hosting/group.rb",
    "test/helper.rb",
    "test/test_unit-hosting.rb",
    "unit-hosting.gemspec"
  ]
  s.homepage = %q{http://github.com/tumf/unit-hosting}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.1}
  s.summary = %q{unit-hosting command line tool}
  s.test_files = [
    "test/helper.rb",
    "test/test_unit-hosting.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mutter>, [">= 0"])
      s.add_runtime_dependency(%q<keystorage>, ["> 0.1"])
      s.add_runtime_dependency(%q<mechanize>, [">= 1.0.0"])
      s.add_runtime_dependency(%q<highline>, ["> 1.6"])
      s.add_runtime_dependency(%q<progressbar>, [">= 0.9.0"])
      s.add_runtime_dependency(%q<httpclient>, [">= 2.1.6.1"])
      s.add_runtime_dependency(%q<command-line-utils>, [">= 0.0.1"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<mutter>, [">= 0"])
      s.add_dependency(%q<keystorage>, ["> 0.1"])
      s.add_dependency(%q<mechanize>, [">= 1.0.0"])
      s.add_dependency(%q<highline>, ["> 1.6"])
      s.add_dependency(%q<progressbar>, [">= 0.9.0"])
      s.add_dependency(%q<httpclient>, [">= 2.1.6.1"])
      s.add_dependency(%q<command-line-utils>, [">= 0.0.1"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<mutter>, [">= 0"])
    s.add_dependency(%q<keystorage>, ["> 0.1"])
    s.add_dependency(%q<mechanize>, [">= 1.0.0"])
    s.add_dependency(%q<highline>, ["> 1.6"])
    s.add_dependency(%q<progressbar>, [">= 0.9.0"])
    s.add_dependency(%q<httpclient>, [">= 2.1.6.1"])
    s.add_dependency(%q<command-line-utils>, [">= 0.0.1"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

